### ISSUE TITLE
[A14] [Crash] MODE_WORLD_READABLE

### ISSUE THREAD

**Issue by Emulond** [RichardLuo0/global-icon-pack-android#4]
The application crashes upon launching, because it uses a deprecated method:

```
Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: samsung
[Device Model]: SM-S908B
[Display]: ExtremeROM v4.6 (UP1A.231005.007.S908BXXSAEXE3)
[Android Version]: 14
[Android API Level]: 34
[System Locale]: ru_RU
[Process ID]: 10687
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.richardluo.globalIconPack
[Version Name]: 0.0.7
[Version Code]: 7
[Target SDK]: 35
[Min SDK]: 34
[Error Type]: JVM
[Crash Time]: 2024-12-10T23:34:27.239
[Stack Trace]:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.richardluo.globalIconPack/com.richardluo.globalIconPack.ui.MainActivity}: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:774)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:52)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:83)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:76)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:221)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:185)
	at android.os.Looper.loop(Unknown Source:83)
	at android.app.ActivityThread.main(Unknown Source:107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:334)
Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
	at android.app.ContextImpl.checkMode(Unknown Source:31)
	at android.app.ContextImpl.getSharedPreferences(Unknown Source:15)
	at android.app.ContextImpl.getSharedPreferences(Unknown Source:52)
	at android.content.ContextWrapper.getSharedPreferences(Unknown Source:2)
	at com.richardluo.globalIconPack.ui.MainActivity.onCreate(Unknown Source:12)
	at android.app.Activity.performCreate(Unknown Source:115)
	at android.app.Activity.performCreate(Unknown Source:1)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:524)
	... 12 more
```
Refer to: https://stackoverflow.com/questions/39121052/java-lang-securityexception-mode-world-readable-no-longer-supported.

**Comment by RichardLuo0** [comment]
You will need to enable it in lsposed first. This is how XSharedPreferences work. 
See also: https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences
